### PR TITLE
Smart banners and Instant apps

### PR DESCRIPTION
**Pull request by ryancarlson**
- Include meta tag for iOS smart banners support
- Tweak configuration to allow .well_known directory to be copied during build in support of Android instant apps.

### CODE REVIEW

**Comment by ryancarlson** [comment]
@sheldond could you review these small tweaks here? I've run the build locally and see that both are working. I will squash before merging if approved two eliminate the reverted commit and its original commit.

**Comment by ryancarlson** [comment]
This issue report cued me into how to include the .well_known directory, for reference: https://github.com/middleman/middleman/issues/1243

**Review by sheldond — APPROVED** [review]
Looks good! Thanks for the link to the middleman issue!

**Comment by ryancarlson** [comment]
Thanks!!

**Pull request merged**
