### PR TITLE
Build with travis

### PR DESCRIPTION
**Pull request by ryancarlson**

### CODE REVIEW

**Comment by ryancarlson** [comment]
@sheldond hey just a heads up that this PR will enable travis-ci to build the project on a scheduled job. it will push the site to S3 where it will be distributed through CloudFront. This will get it on a common platform w/ our other static sites, allow SSL and set it up for universal linking.

**Review by sheldond — CHANGES_REQUESTED** [review]
Thanks Ryan, that sounds great! 👍 

There are a few more things to update in order to move everything over to travis:

1. Before running `middleman build` we'll want to update the translation files (so that translation updates are automated). This is a separate step. Currently it's handled using [this rake task](https://github.com/Indigitous/godtools-web/blob/master/Rakefile#L58). In order to keep all this deploy logic all in one place, I think we could update this rake task and then have travis run the rake task instead.

2. Currently Middleman is configured to handle the deployment, [the config is here](https://github.com/Indigitous/godtools-web/blob/master/config.rb#L155). Since travis will be handling that step instead, I think it would be a good idea to remove the middleman deploy config.

3. After we merge this we should disable the Heroku account that's currently running the daily deploys.

4. We'll need to update the readme file.

Feel free to let me know if you'd like any help with these steps! I think we are already planning to do some work on this project in the coming weeks. Thanks!

**Comment by ryancarlson** [comment]
@sheldond I believe I have addressed most your feedback.
 - locale files are being updated
 - readme was updated
 - middleman config removed.

I have not updated heroku yet, though.

One important change is that I removed the section that commits the locale files to version control. I was having trouble getting the git configurations working correctly. As I thought about it, so long as the locale files are present at the time middleman updates, it may not be necessary to commit them to version control.

The translated phrases are already versioned in the translation tool, and in the old API as well. Unless there is a technical reason why they must be committed that I'm not aware of, do you have concern about moving ahead this way?

**Comment by ryancarlson** [comment]
Also, this is admittedly a messy PR, so I will definitely squash before merging.

**Review by sheldond — APPROVED** [review]
Thanks Ryan!

I think your changes look good! Good job!

Regarding committing the locale files: you're right, I don't think it's necessary to commit the updated locale files. The only downside would be that the repo will become out of date for development, but I don't think that's an issue, as it would be fairly easy to manually update when needed.

A couple more small things:

1. After we make the switch, we'll also want to disable the Github pages hosting.

2. For https, we can update this line to use https: https://github.com/Indigitous/godtools-web/blob/master/config.rb#L13

**Comment by ryancarlson** [comment]
Thanks @sheldond ! I'll make that https update and disable gh-pages after things are finished in CloudFront.

**Pull request merged**
